FROM node:20-alpine

WORKDIR /app
COPY src/shared/music-discovery ./src/shared/music-discovery
COPY src/web-discovery ./src/web-discovery

USER node
EXPOSE 8081
CMD ["node", "src/web-discovery/server.js"]
