apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - discovery-deployment.yaml
  - discovery-service.yaml
  - discovery-ingress.yaml
  - discovery-leads-pvc.yaml
